
# dataroaster version.
dataroaster_version: 4.1.0-SNAPSHOT

# dataroaster home directory.
#dataroaster_home_dir: /opt/dataroaster

# dataroaster log directory.
#dataroaster_log_dir: /data/dataroaster/logs

# execution user to run dataroaster applications.
#dataroaster_exec_user: dataroaster

# dataroaster apiserver home directory.
#apiserver_home_dir: "{{ dataroaster_home_dir }}/apiserver"

# dataroaster authorizer home directory.
#authorizer_home_dir: "{{ dataroaster_home_dir }}/authorizer"

# user and password for mysql database of dataroaster.
#mysql_dataroaster_user: dataroaster
#mysql_dataroaster_password: dataroaster123

# user and password for mysql database of vault.
#mysql_vault_user: dataroaster
#mysql_vault_password: dataroaster123

# vault environment variables.
#vault_env:
#  VAULT_ADDR: https://localhost:8200
#  VAULT_SKIP_VERIFY: true